# ha-tunnel-addon/config.yaml
name: "HATUN Addon"
version: "1.0.0"
slug: "hatun"
description: "Connects your Home Assistant to the Secure Tunneling Service."
url: "https://github.com/nawikre1/hap-addon"
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: "auto"
hassio_role: "homeassistant"
host_network: true
privileged:
  - NET_ADMIN
options:
  api_key: ""
schema:
  api_key: "password"